apiVersion: v1
kind: Service
metadata:
  name: weather-api-service  # Name of the service
spec:
  type: NodePort  # Expose the service on each Node's IP at a static port
  selector:
    app: weather-api  # Match pods with the label 'app: weather-api'
  ports:
    - protocol: TCP  # Specify the protocol used for communication (TCP in this case) for communication between the service and the pods.
      port: 80  # Port on which the service will be exposed
      targetPort: 4000  # Port on the pods to which traffic will be forwarded
